version: '3'

services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - '6379:6379'
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'

  postgres:
    container_name: postgres
    image: postgres:12
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: auth
    networks:
      - postgres

volumes:
  postgres: {}

networks:
  postgres:
    driver: bridge
